image: registry.gitlab.com/christiantragesser/pypline-ci:dev

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    PACKAGE: pypline-ci
    
services:
- name: docker:stable-dind

stages:
  - test
  - release

test:
  stage: test
  script:
    - pytest -v $CI_PROJECT_DIR/tests
    - pytest --cov pyplineCI $CI_PROJECT_DIR/tests --cov-report html --cov-report term
    - docker build -t $CI_REGISTRY/christiantragesser/pypline-ci -f $CI_PROJECT_DIR/docker/Dockerfile .
    - docker run --rm -i -v /var/run/docker.sock:/var/run/docker.sock $CI_REGISTRY/christiantragesser/pypline-ci python3 -c "from pyplineCI import Pipeline; Pipeline().cve_scan('alpine:latest')"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/christiantragesser/pypline-ci | grep -e "The push refers to" -e latest
  only:
    - master
  artifacts:
    paths:
    - "$CI_PROJECT_DIR/htmlcov"
    expire_in: 1 week
  
release_fakos:
   stage: release
   script:
    - docker build -t $CI_REGISTRY/christiantragesser/pypline-ci:fakos -f $CI_PROJECT_DIR/docker/Dockerfile.pypline-fakos .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/christiantragesser/pypline-ci:fakos | grep -e "The push refers to" -e latest
   only:
     - master
  
release_poc:
   stage: release
   script:
    - docker build -t $CI_REGISTRY/christiantragesser/pypline-ci:poc -f $CI_PROJECT_DIR/docker/Dockerfile.pypline-poc .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/christiantragesser/pypline-ci:poc | grep -e "The push refers to" -e latest
   only:
     - master
  
release_pypi:
   stage: release
   script:
    - MAJOR="0"
    - MINOR="2"
    - LATEST=$(pip3 search $PACKAGE | grep $PACKAGE | awk '{print $2}' | tr -d \( | tr -d \) | awk -F '.' '{print $3}')
    - NEW=$((LATEST + 1))
    - sed -i -e "s/PATCH/$NEW/" setup.py
    - mkdir $CI_PROJECT_DIR/pyplineCI
    - echo "from .pyplineCI import *" > $CI_PROJECT_DIR/pyplineCI/__init__.py
    - cp $CI_PROJECT_DIR/pyplineCI.py $CI_PROJECT_DIR/pyplineCI/pyplineCI.py
    - cp $CI_PROJECT_DIR/README.md $CI_PROJECT_DIR/pyplineCI/README.md
    - python3 setup.py sdist
    - pip3 install $CI_PROJECT_DIR/dist/pypline-ci-${MAJOR}.${MINOR}.${NEW}.tar.gz
    - python3 -c 'from pyplineCI import Pipeline'
    - twine upload dist/*
   only:
     - master