image: registry.gitlab.com/christiantragesser/pypline-ci:dev

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    PACKAGE: pypline-ci
    
services:
- name: docker:stable-dind
  command: ["--registry-mirror=https://dockerhub-mirror0.artifactory.asynchrony.com"] 

stages:
  - test
  - release

test_2.7:
  stage: test
  script:
    - pytest $CI_PROJECT_DIR/tests
    - docker build -t $CI_REGISTRY/christiantragesser/pypline-ci:latest .
    - docker tag $CI_REGISTRY/christiantragesser/pypline-ci:latest $CI_REGISTRY/christiantragesser/pypline-ci:2.7
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/christiantragesser/pypline-ci:latest | grep -e "The push refers to" -e latest
    - docker push $CI_REGISTRY/christiantragesser/pypline-ci:2.7 | grep -e "The push refers to" -e latest
  only:
    - master

test_3:
  stage: test
  script:
    - docker run --rm -i -v $CI_PROJECT_DIR:/tmp -v /var/run/docker.sock:/var/run/docker.sock $CI_REGISTRY/christiantragesser/pypline-ci:3 sh -c 'pytest /tmp/tests'
    - docker build -t $CI_REGISTRY/christiantragesser/pypline-ci:3 -f $CI_PROJECT_DIR/Dockerfile-3 .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/christiantragesser/pypline-ci:3 | grep -e "The push refers to" -e latest
  only:
    - master
  
release_fakos:
   stage: release
   script:
    - docker build -t $CI_REGISTRY/christiantragesser/pypline-ci:fakos -f $CI_PROJECT_DIR/Dockerfile.pypline-fakos .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/christiantragesser/pypline-ci:fakos | grep -e "The push refers to" -e latest
   only:
     - master
  
release_poc:
   stage: release
   script:
    - docker build -t $CI_REGISTRY/christiantragesser/pypline-ci:poc -f $CI_PROJECT_DIR/Dockerfile.pypline-poc .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/christiantragesser/pypline-ci:poc | grep -e "The push refers to" -e latest
   only:
     - master
  
release_pypi:
   stage: release
   script:
    - PATCH=$(pip search $PACKAGE | grep $PACKAGE | awk '{print $2}' | tr -d \( | tr -d \) | awk -F '.' '{print $3}')
    - NEW=$((PATCH + 1))
    - sed -i -e "s/PATCH/$NEW/" setup.py
    - mkdir $CI_PROJECT_DIR/pyplineCI
    - echo "from .pyplineCI import *" > $CI_PROJECT_DIR/pyplineCI/__init__.py
    - cp README.md README.txt
    - cp $CI_PROJECT_DIR/pyplineCI.py $CI_PROJECT_DIR/pyplineCI/pyplineCI.py
    - python setup.py sdist
    - pip install $CI_PROJECT_DIR/dist/pypline-ci-0.1.${NEW}.tar.gz
    - python -c 'from pyplineCI import Pipeline'
    - twine upload dist/*
   only:
     - master