FROM docker:latest

COPY requirements/requirements.txt /tmp/requirements.txt
COPY requirements/requirements-dev.txt /tmp/requirements-dev.txt

RUN apk -U add python py-pip --no-cache && \
pip install --upgrade pip --no-cache-dir && \
pip install -r /tmp/requirements.txt --no-cache-dir && \
pip install -r /tmp/requirements-dev.txt --no-cache-dir